openapi: 3.0.0
info:
  title: API des Masques
  version: "1.0"
  description: Une API simple pour gérer les masques avec MongoDB et PostgreSQL
servers:
  - url: http://localhost:3000
    description: Serveur de développement
paths:
  /mongodb/masks:
    get:
      summary: Récupère une liste de tous les masques (MongoDB)
      responses:
        '200':
          description: Une liste de masques
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mask'
    post:
      summary: Ajoute un nouveau masque (MongoDB)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mask'
      responses:
        '201':
          description: Masque créé
  /postgres/masks:
    get:
      summary: Récupère une liste de tous les masques (PostgreSQL)
      responses:
        '200':
          description: Une liste de masques
components:
  schemas:
    Mask:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        mask_json:
          type: object
